import React from 'react';
import { Sparkles, ArrowRight } from 'lucide-react';

const Recommendations = () => {
  return (
    <div className="flex flex-col gap-8">
      <header className="flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 mb-1">AI Recommendations</h1>
          <p className="text-sm text-slate-500">Discover trending topics and content ideas generated by AI.</p>
        </div>
        <div className="flex gap-4">
          <button className="inline-flex items-center justify-center gap-2 px-4 py-2 bg-primary hover:bg-primary-light text-white rounded-md text-sm font-medium transition-all hover:-translate-y-[1px]">
            <Sparkles size={16} />
            Generate Ideas
          </button>
        </div>
      </header>

      <div className="bg-white border border-slate-200 rounded-lg shadow-sm p-8 text-center flex flex-col items-center justify-center text-slate-500">
          <Sparkles size={48} className="mb-4 text-slate-300" />
          <h3 className="text-lg font-medium text-slate-900 mb-1">Awaiting Data</h3>
          <p className="max-w-sm mb-4">We need more content data to generate personalized AI recommendations. Keep adding sources!</p>
          <button className="inline-flex items-center justify-center gap-2 px-4 py-2 border border-slate-300 bg-white hover:bg-slate-50 text-slate-700 rounded-md text-sm font-medium transition-colors">
              Go to Sources <ArrowRight size={16} />
          </button>
      </div>
    </div>
  );
};

export default Recommendations;
