import React, { useState } from 'react';
import { Sparkles, ArrowRight, Save } from 'lucide-react';

const Recommendations = () => {
  const [showForm, setShowForm] = useState(false);

  return (
    <div className="flex flex-col gap-8">
      <header className="flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 mb-1">AI Recommendations</h1>
          <p className="text-sm text-slate-500">Discover trending topics and content ideas generated by AI.</p>
        </div>
        <div className="flex gap-4">
          <button 
            onClick={() => setShowForm(!showForm)}
            className="inline-flex items-center justify-center gap-2 px-4 py-2 bg-primary hover:bg-primary-light text-white rounded-md text-sm font-medium transition-all hover:-translate-y-[1px]"
          >
            {showForm ? 'Cancel' : <><Sparkles size={16} /> Generate Ideas</>}
          </button>
        </div>
      </header>

      {showForm && (
        <div className="bg-gradient-to-br from-indigo-50 to-purple-50 border border-indigo-100 rounded-lg shadow-sm p-6 mb-4">
          <div className="flex items-center gap-2 mb-4">
            <Sparkles className="text-indigo-500" size={20} />
            <h2 className="text-lg font-semibold text-slate-900">Custom Idea Generation</h2>
          </div>
          <form className="flex flex-col gap-4 max-w-2xl">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Target Audience</label>
              <input type="text" placeholder="e.g. Frontend Developers, Tech Enthusiasts" className="w-full px-4 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent bg-white/70" />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Content Type</label>
                <select className="w-full px-4 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent bg-white/70">
                  <option value="blog">Blog Post</option>
                  <option value="video">YouTube Video</option>
                  <option value="thread">Twitter Thread</option>
                  <option value="newsletter">Newsletter</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Tone / Style</label>
                <select className="w-full px-4 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent bg-white/70">
                  <option value="informative">Informative & Educational</option>
                  <option value="casual">Casual & Conversational</option>
                  <option value="professional">Professional & Authoritative</option>
                  <option value="humorous">Humorous & Witty</option>
                </select>
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Specific Keywords / Topics (Optional)</label>
              <input type="text" placeholder="e.g. React 19, AI Tools" className="w-full px-4 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent bg-white/70" />
            </div>
            <div className="pt-2">
              <button type="button" className="inline-flex items-center justify-center gap-2 px-6 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-md text-sm font-medium transition-colors shadow-sm shadow-indigo-200">
                <Sparkles size={16} /> Generate Custom Ideas
              </button>
            </div>
          </form>
        </div>
      )}

      {!showForm && (
        <div className="bg-white border border-slate-200 rounded-lg shadow-sm p-8 text-center flex flex-col items-center justify-center text-slate-500">
            <Sparkles size={48} className="mb-4 text-slate-300" />
            <h3 className="text-lg font-medium text-slate-900 mb-1">Awaiting Data</h3>
            <p className="max-w-sm mb-4">We need more content data to generate personalized AI recommendations automatically. Or you can request custom ideas now.</p>
            <button onClick={() => setShowForm(true)} className="inline-flex items-center justify-center gap-2 px-4 py-2 border border-slate-300 bg-white hover:bg-slate-50 text-slate-700 rounded-md text-sm font-medium transition-colors">
                Generate Custom Ideas <ArrowRight size={16} />
            </button>
        </div>
      )}
    </div>
  );
};

export default Recommendations;
